from __future__ import annotations


MAX_ADVISOR_PATCH_EDITS = 5
MAX_ADVISOR_EDIT_TEXT_CHARS = 420
MAX_ADVISOR_REPLACE_TEXT_CHARS = 700
MAX_ADVISOR_TOTAL_PATCH_TEXT_CHARS = 900
MAX_ADVISOR_APPEND_TEXT_CHARS = 360
ADVISOR_PATCH_MAX_CHANGE_RATIO = 0.06
ADVISOR_PATCH_MIN_CHANGE_CHARS = 400
ADVISOR_STAGE1_BATCH_SIZE = 2
ADVISOR_STAGE1_MAX_TOKENS = 1200
ADVISOR_STAGE2_MAX_TOKENS = 1000
ADVISOR_SECTION_BLOCK_CHARS = 2400
ADVISOR_SECTION_BLOCK_PREVIEW_CHARS = 180
ADVISOR_MAX_EDITABLE_BLOCKS = 2
